<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: reservation.proto
//   Date: 2018-07-27 14:00:28

namespace PlentyServices\TravelLibs\Protobuf\Product {

  class Fare extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $fare_id = null;
    
    /**  @var string */
    public $farebase = null;
    
    /**  @var string */
    public $discount = null;
    
    /**  @var string */
    public $pax_type = null;
    
    /**  @var int */
    public $pax_holds = null;
    
    /**  @var float */
    public $retail_exchange = null;
    
    /**  @var float */
    public $purchase_exchange = null;
    
    /**  @var float */
    public $purchase_nett = null;
    
    /**  @var float */
    public $purchase_gross = null;
    
    /**  @var string */
    public $purchase_currency = null;
    
    /**  @var float */
    public $purchase_commission_percentage = null;
    
    /**  @var float */
    public $purchase_commission_amount = null;
    
    /**  @var float */
    public $retail_price = null;
    
    /**  @var string */
    public $retail_currency = null;
    
    /**  @var boolean */
    public $calc_from_gross = null;
    
    /**  @var boolean */
    public $round_retail_price = null;
    
    /**  @var string */
    public $round_retail_price_method = null;
    
    /**  @var string */
    public $display = null;
    
    /**  @var string */
    public $display_description = null;
    
    /**  @var float */
    public $markup_percentage = null;
    
    /**  @var float */
    public $markup_amount = null;
    
    /**  @var float */
    public $margin_percentage = null;
    
    /**  @var float */
    public $commission_peer_percentage = null;
    
    /**  @var float */
    public $commission_peer_amount = null;
    
    /**  @var float */
    public $commission_broker_percentage = null;
    
    /**  @var float */
    public $commission_broker_amount = null;
    
    /**  @var string */
    public $service_class = null;
    
    /**  @var string */
    public $cabin_class = null;
    
    /**  @var string */
    public $payable = null;
    
    /**  @var int */
    public $quantity = null;
    
    /**  @var \PlentyServices\TravelLibs\Protobuf\Product\Fare\TagCondition[]  */
    public $tag_conditions = array();
    
    /**  @var \PlentyServices\TravelLibs\Protobuf\Product\Fare\Charge[]  */
    public $charges = array();
    
    /**  @var \PlentyServices\TravelLibs\Protobuf\Person[]  */
    public $passengers = array();
    
    /**  @var string */
    public $status = null;
    
    /**  @var string */
    public $condition_code = null;
    
    /**  @var \PlentyServices\TravelLibs\Protobuf\Availability */
    public $availability = null;
    
    /**  @var \PlentyServices\TravelLibs\Protobuf\Message[]  */
    public $messages = array();
    
    /**  @var string */
    public $offer_text = null;
    
    /**  @var string */
    public $voucher_text = null;
    
    /**  @var string */
    public $booking_class = null;
    
    /**  @var int */
    public $kilometers = null;
    
    /**  @var boolean */
    public $hidden = null;
    
    /**  @var boolean */
    public $hide_retail_price = null;
    
    /**  @var string */
    public $confirmation_number = null;
    
    /**  @var string */
    public $external_reference = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'PlentyServicesTravelLibs.Product.Fare');

      // OPTIONAL STRING fare_id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "fare_id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING farebase = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "farebase";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING discount = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "discount";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING pax_type = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "pax_type";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT32 pax_holds = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "pax_holds";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT retail_exchange = 9
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 9;
      $f->name      = "retail_exchange";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT purchase_exchange = 10
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10;
      $f->name      = "purchase_exchange";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT purchase_nett = 11
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 11;
      $f->name      = "purchase_nett";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT purchase_gross = 12
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 12;
      $f->name      = "purchase_gross";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING purchase_currency = 13
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 13;
      $f->name      = "purchase_currency";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT purchase_commission_percentage = 14
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 14;
      $f->name      = "purchase_commission_percentage";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT purchase_commission_amount = 15
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 15;
      $f->name      = "purchase_commission_amount";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT retail_price = 16
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 16;
      $f->name      = "retail_price";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING retail_currency = 34
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 34;
      $f->name      = "retail_currency";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL BOOL calc_from_gross = 17
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 17;
      $f->name      = "calc_from_gross";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL BOOL round_retail_price = 18
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 18;
      $f->name      = "round_retail_price";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING round_retail_price_method = 19
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 19;
      $f->name      = "round_retail_price_method";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING display = 20
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 20;
      $f->name      = "display";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING display_description = 21
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 21;
      $f->name      = "display_description";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT markup_percentage = 23
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 23;
      $f->name      = "markup_percentage";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT markup_amount = 24
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 24;
      $f->name      = "markup_amount";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT margin_percentage = 25
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 25;
      $f->name      = "margin_percentage";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT commission_peer_percentage = 26
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 26;
      $f->name      = "commission_peer_percentage";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT commission_peer_amount = 27
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 27;
      $f->name      = "commission_peer_amount";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT commission_broker_percentage = 28
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 28;
      $f->name      = "commission_broker_percentage";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL FLOAT commission_broker_amount = 29
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 29;
      $f->name      = "commission_broker_amount";
      $f->type      = \DrSlump\Protobuf::TYPE_FLOAT;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING service_class = 31
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 31;
      $f->name      = "service_class";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING cabin_class = 32
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 32;
      $f->name      = "cabin_class";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING payable = 33
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 33;
      $f->name      = "payable";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT32 quantity = 35
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 35;
      $f->name      = "quantity";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED MESSAGE tag_conditions = 36
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 36;
      $f->name      = "tag_conditions";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\PlentyServices\TravelLibs\Protobuf\Product\Fare\TagCondition';
      $descriptor->addField($f);

      // REPEATED MESSAGE charges = 40
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 40;
      $f->name      = "charges";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\PlentyServices\TravelLibs\Protobuf\Product\Fare\Charge';
      $descriptor->addField($f);

      // REPEATED MESSAGE passengers = 41
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 41;
      $f->name      = "passengers";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\PlentyServices\TravelLibs\Protobuf\Person';
      $descriptor->addField($f);

      // OPTIONAL STRING status = 42
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 42;
      $f->name      = "status";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING condition_code = 50
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 50;
      $f->name      = "condition_code";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE availability = 51
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 51;
      $f->name      = "availability";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\PlentyServices\TravelLibs\Protobuf\Availability';
      $descriptor->addField($f);

      // REPEATED MESSAGE messages = 52
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 52;
      $f->name      = "messages";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\PlentyServices\TravelLibs\Protobuf\Message';
      $descriptor->addField($f);

      // OPTIONAL STRING offer_text = 53
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 53;
      $f->name      = "offer_text";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING voucher_text = 55
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 55;
      $f->name      = "voucher_text";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING booking_class = 56
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 56;
      $f->name      = "booking_class";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT32 kilometers = 57
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 57;
      $f->name      = "kilometers";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL BOOL hidden = 58
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 58;
      $f->name      = "hidden";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL BOOL hide_retail_price = 59
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 59;
      $f->name      = "hide_retail_price";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING confirmation_number = 60
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 60;
      $f->name      = "confirmation_number";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING external_reference = 61
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 61;
      $f->name      = "external_reference";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <fare_id> has a value
     *
     * @return boolean
     */
    public function hasFareId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <fare_id> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearFareId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <fare_id> value
     *
     * @return string
     */
    public function getFareId(){
      return $this->_get(1);
    }
    
    /**
     * Set <fare_id> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setFareId( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <farebase> has a value
     *
     * @return boolean
     */
    public function hasFarebase(){
      return $this->_has(2);
    }
    
    /**
     * Clear <farebase> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearFarebase(){
      return $this->_clear(2);
    }
    
    /**
     * Get <farebase> value
     *
     * @return string
     */
    public function getFarebase(){
      return $this->_get(2);
    }
    
    /**
     * Set <farebase> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setFarebase( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <discount> has a value
     *
     * @return boolean
     */
    public function hasDiscount(){
      return $this->_has(5);
    }
    
    /**
     * Clear <discount> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearDiscount(){
      return $this->_clear(5);
    }
    
    /**
     * Get <discount> value
     *
     * @return string
     */
    public function getDiscount(){
      return $this->_get(5);
    }
    
    /**
     * Set <discount> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setDiscount( $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <pax_type> has a value
     *
     * @return boolean
     */
    public function hasPaxType(){
      return $this->_has(6);
    }
    
    /**
     * Clear <pax_type> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearPaxType(){
      return $this->_clear(6);
    }
    
    /**
     * Get <pax_type> value
     *
     * @return string
     */
    public function getPaxType(){
      return $this->_get(6);
    }
    
    /**
     * Set <pax_type> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setPaxType( $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <pax_holds> has a value
     *
     * @return boolean
     */
    public function hasPaxHolds(){
      return $this->_has(7);
    }
    
    /**
     * Clear <pax_holds> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearPaxHolds(){
      return $this->_clear(7);
    }
    
    /**
     * Get <pax_holds> value
     *
     * @return int
     */
    public function getPaxHolds(){
      return $this->_get(7);
    }
    
    /**
     * Set <pax_holds> value
     *
     * @param int $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setPaxHolds( $value){
      return $this->_set(7, $value);
    }
    
    /**
     * Check if <retail_exchange> has a value
     *
     * @return boolean
     */
    public function hasRetailExchange(){
      return $this->_has(9);
    }
    
    /**
     * Clear <retail_exchange> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearRetailExchange(){
      return $this->_clear(9);
    }
    
    /**
     * Get <retail_exchange> value
     *
     * @return float
     */
    public function getRetailExchange(){
      return $this->_get(9);
    }
    
    /**
     * Set <retail_exchange> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setRetailExchange( $value){
      return $this->_set(9, $value);
    }
    
    /**
     * Check if <purchase_exchange> has a value
     *
     * @return boolean
     */
    public function hasPurchaseExchange(){
      return $this->_has(10);
    }
    
    /**
     * Clear <purchase_exchange> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearPurchaseExchange(){
      return $this->_clear(10);
    }
    
    /**
     * Get <purchase_exchange> value
     *
     * @return float
     */
    public function getPurchaseExchange(){
      return $this->_get(10);
    }
    
    /**
     * Set <purchase_exchange> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setPurchaseExchange( $value){
      return $this->_set(10, $value);
    }
    
    /**
     * Check if <purchase_nett> has a value
     *
     * @return boolean
     */
    public function hasPurchaseNett(){
      return $this->_has(11);
    }
    
    /**
     * Clear <purchase_nett> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearPurchaseNett(){
      return $this->_clear(11);
    }
    
    /**
     * Get <purchase_nett> value
     *
     * @return float
     */
    public function getPurchaseNett(){
      return $this->_get(11);
    }
    
    /**
     * Set <purchase_nett> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setPurchaseNett( $value){
      return $this->_set(11, $value);
    }
    
    /**
     * Check if <purchase_gross> has a value
     *
     * @return boolean
     */
    public function hasPurchaseGross(){
      return $this->_has(12);
    }
    
    /**
     * Clear <purchase_gross> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearPurchaseGross(){
      return $this->_clear(12);
    }
    
    /**
     * Get <purchase_gross> value
     *
     * @return float
     */
    public function getPurchaseGross(){
      return $this->_get(12);
    }
    
    /**
     * Set <purchase_gross> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setPurchaseGross( $value){
      return $this->_set(12, $value);
    }
    
    /**
     * Check if <purchase_currency> has a value
     *
     * @return boolean
     */
    public function hasPurchaseCurrency(){
      return $this->_has(13);
    }
    
    /**
     * Clear <purchase_currency> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearPurchaseCurrency(){
      return $this->_clear(13);
    }
    
    /**
     * Get <purchase_currency> value
     *
     * @return string
     */
    public function getPurchaseCurrency(){
      return $this->_get(13);
    }
    
    /**
     * Set <purchase_currency> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setPurchaseCurrency( $value){
      return $this->_set(13, $value);
    }
    
    /**
     * Check if <purchase_commission_percentage> has a value
     *
     * @return boolean
     */
    public function hasPurchaseCommissionPercentage(){
      return $this->_has(14);
    }
    
    /**
     * Clear <purchase_commission_percentage> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearPurchaseCommissionPercentage(){
      return $this->_clear(14);
    }
    
    /**
     * Get <purchase_commission_percentage> value
     *
     * @return float
     */
    public function getPurchaseCommissionPercentage(){
      return $this->_get(14);
    }
    
    /**
     * Set <purchase_commission_percentage> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setPurchaseCommissionPercentage( $value){
      return $this->_set(14, $value);
    }
    
    /**
     * Check if <purchase_commission_amount> has a value
     *
     * @return boolean
     */
    public function hasPurchaseCommissionAmount(){
      return $this->_has(15);
    }
    
    /**
     * Clear <purchase_commission_amount> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearPurchaseCommissionAmount(){
      return $this->_clear(15);
    }
    
    /**
     * Get <purchase_commission_amount> value
     *
     * @return float
     */
    public function getPurchaseCommissionAmount(){
      return $this->_get(15);
    }
    
    /**
     * Set <purchase_commission_amount> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setPurchaseCommissionAmount( $value){
      return $this->_set(15, $value);
    }
    
    /**
     * Check if <retail_price> has a value
     *
     * @return boolean
     */
    public function hasRetailPrice(){
      return $this->_has(16);
    }
    
    /**
     * Clear <retail_price> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearRetailPrice(){
      return $this->_clear(16);
    }
    
    /**
     * Get <retail_price> value
     *
     * @return float
     */
    public function getRetailPrice(){
      return $this->_get(16);
    }
    
    /**
     * Set <retail_price> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setRetailPrice( $value){
      return $this->_set(16, $value);
    }
    
    /**
     * Check if <retail_currency> has a value
     *
     * @return boolean
     */
    public function hasRetailCurrency(){
      return $this->_has(34);
    }
    
    /**
     * Clear <retail_currency> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearRetailCurrency(){
      return $this->_clear(34);
    }
    
    /**
     * Get <retail_currency> value
     *
     * @return string
     */
    public function getRetailCurrency(){
      return $this->_get(34);
    }
    
    /**
     * Set <retail_currency> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setRetailCurrency( $value){
      return $this->_set(34, $value);
    }
    
    /**
     * Check if <calc_from_gross> has a value
     *
     * @return boolean
     */
    public function hasCalcFromGross(){
      return $this->_has(17);
    }
    
    /**
     * Clear <calc_from_gross> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearCalcFromGross(){
      return $this->_clear(17);
    }
    
    /**
     * Get <calc_from_gross> value
     *
     * @return boolean
     */
    public function getCalcFromGross(){
      return $this->_get(17);
    }
    
    /**
     * Set <calc_from_gross> value
     *
     * @param boolean $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setCalcFromGross( $value){
      return $this->_set(17, $value);
    }
    
    /**
     * Check if <round_retail_price> has a value
     *
     * @return boolean
     */
    public function hasRoundRetailPrice(){
      return $this->_has(18);
    }
    
    /**
     * Clear <round_retail_price> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearRoundRetailPrice(){
      return $this->_clear(18);
    }
    
    /**
     * Get <round_retail_price> value
     *
     * @return boolean
     */
    public function getRoundRetailPrice(){
      return $this->_get(18);
    }
    
    /**
     * Set <round_retail_price> value
     *
     * @param boolean $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setRoundRetailPrice( $value){
      return $this->_set(18, $value);
    }
    
    /**
     * Check if <round_retail_price_method> has a value
     *
     * @return boolean
     */
    public function hasRoundRetailPriceMethod(){
      return $this->_has(19);
    }
    
    /**
     * Clear <round_retail_price_method> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearRoundRetailPriceMethod(){
      return $this->_clear(19);
    }
    
    /**
     * Get <round_retail_price_method> value
     *
     * @return string
     */
    public function getRoundRetailPriceMethod(){
      return $this->_get(19);
    }
    
    /**
     * Set <round_retail_price_method> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setRoundRetailPriceMethod( $value){
      return $this->_set(19, $value);
    }
    
    /**
     * Check if <display> has a value
     *
     * @return boolean
     */
    public function hasDisplay(){
      return $this->_has(20);
    }
    
    /**
     * Clear <display> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearDisplay(){
      return $this->_clear(20);
    }
    
    /**
     * Get <display> value
     *
     * @return string
     */
    public function getDisplay(){
      return $this->_get(20);
    }
    
    /**
     * Set <display> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setDisplay( $value){
      return $this->_set(20, $value);
    }
    
    /**
     * Check if <display_description> has a value
     *
     * @return boolean
     */
    public function hasDisplayDescription(){
      return $this->_has(21);
    }
    
    /**
     * Clear <display_description> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearDisplayDescription(){
      return $this->_clear(21);
    }
    
    /**
     * Get <display_description> value
     *
     * @return string
     */
    public function getDisplayDescription(){
      return $this->_get(21);
    }
    
    /**
     * Set <display_description> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setDisplayDescription( $value){
      return $this->_set(21, $value);
    }
    
    /**
     * Check if <markup_percentage> has a value
     *
     * @return boolean
     */
    public function hasMarkupPercentage(){
      return $this->_has(23);
    }
    
    /**
     * Clear <markup_percentage> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearMarkupPercentage(){
      return $this->_clear(23);
    }
    
    /**
     * Get <markup_percentage> value
     *
     * @return float
     */
    public function getMarkupPercentage(){
      return $this->_get(23);
    }
    
    /**
     * Set <markup_percentage> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setMarkupPercentage( $value){
      return $this->_set(23, $value);
    }
    
    /**
     * Check if <markup_amount> has a value
     *
     * @return boolean
     */
    public function hasMarkupAmount(){
      return $this->_has(24);
    }
    
    /**
     * Clear <markup_amount> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearMarkupAmount(){
      return $this->_clear(24);
    }
    
    /**
     * Get <markup_amount> value
     *
     * @return float
     */
    public function getMarkupAmount(){
      return $this->_get(24);
    }
    
    /**
     * Set <markup_amount> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setMarkupAmount( $value){
      return $this->_set(24, $value);
    }
    
    /**
     * Check if <margin_percentage> has a value
     *
     * @return boolean
     */
    public function hasMarginPercentage(){
      return $this->_has(25);
    }
    
    /**
     * Clear <margin_percentage> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearMarginPercentage(){
      return $this->_clear(25);
    }
    
    /**
     * Get <margin_percentage> value
     *
     * @return float
     */
    public function getMarginPercentage(){
      return $this->_get(25);
    }
    
    /**
     * Set <margin_percentage> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setMarginPercentage( $value){
      return $this->_set(25, $value);
    }
    
    /**
     * Check if <commission_peer_percentage> has a value
     *
     * @return boolean
     */
    public function hasCommissionPeerPercentage(){
      return $this->_has(26);
    }
    
    /**
     * Clear <commission_peer_percentage> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearCommissionPeerPercentage(){
      return $this->_clear(26);
    }
    
    /**
     * Get <commission_peer_percentage> value
     *
     * @return float
     */
    public function getCommissionPeerPercentage(){
      return $this->_get(26);
    }
    
    /**
     * Set <commission_peer_percentage> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setCommissionPeerPercentage( $value){
      return $this->_set(26, $value);
    }
    
    /**
     * Check if <commission_peer_amount> has a value
     *
     * @return boolean
     */
    public function hasCommissionPeerAmount(){
      return $this->_has(27);
    }
    
    /**
     * Clear <commission_peer_amount> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearCommissionPeerAmount(){
      return $this->_clear(27);
    }
    
    /**
     * Get <commission_peer_amount> value
     *
     * @return float
     */
    public function getCommissionPeerAmount(){
      return $this->_get(27);
    }
    
    /**
     * Set <commission_peer_amount> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setCommissionPeerAmount( $value){
      return $this->_set(27, $value);
    }
    
    /**
     * Check if <commission_broker_percentage> has a value
     *
     * @return boolean
     */
    public function hasCommissionBrokerPercentage(){
      return $this->_has(28);
    }
    
    /**
     * Clear <commission_broker_percentage> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearCommissionBrokerPercentage(){
      return $this->_clear(28);
    }
    
    /**
     * Get <commission_broker_percentage> value
     *
     * @return float
     */
    public function getCommissionBrokerPercentage(){
      return $this->_get(28);
    }
    
    /**
     * Set <commission_broker_percentage> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setCommissionBrokerPercentage( $value){
      return $this->_set(28, $value);
    }
    
    /**
     * Check if <commission_broker_amount> has a value
     *
     * @return boolean
     */
    public function hasCommissionBrokerAmount(){
      return $this->_has(29);
    }
    
    /**
     * Clear <commission_broker_amount> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearCommissionBrokerAmount(){
      return $this->_clear(29);
    }
    
    /**
     * Get <commission_broker_amount> value
     *
     * @return float
     */
    public function getCommissionBrokerAmount(){
      return $this->_get(29);
    }
    
    /**
     * Set <commission_broker_amount> value
     *
     * @param float $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setCommissionBrokerAmount( $value){
      return $this->_set(29, $value);
    }
    
    /**
     * Check if <service_class> has a value
     *
     * @return boolean
     */
    public function hasServiceClass(){
      return $this->_has(31);
    }
    
    /**
     * Clear <service_class> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearServiceClass(){
      return $this->_clear(31);
    }
    
    /**
     * Get <service_class> value
     *
     * @return string
     */
    public function getServiceClass(){
      return $this->_get(31);
    }
    
    /**
     * Set <service_class> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setServiceClass( $value){
      return $this->_set(31, $value);
    }
    
    /**
     * Check if <cabin_class> has a value
     *
     * @return boolean
     */
    public function hasCabinClass(){
      return $this->_has(32);
    }
    
    /**
     * Clear <cabin_class> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearCabinClass(){
      return $this->_clear(32);
    }
    
    /**
     * Get <cabin_class> value
     *
     * @return string
     */
    public function getCabinClass(){
      return $this->_get(32);
    }
    
    /**
     * Set <cabin_class> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setCabinClass( $value){
      return $this->_set(32, $value);
    }
    
    /**
     * Check if <payable> has a value
     *
     * @return boolean
     */
    public function hasPayable(){
      return $this->_has(33);
    }
    
    /**
     * Clear <payable> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearPayable(){
      return $this->_clear(33);
    }
    
    /**
     * Get <payable> value
     *
     * @return string
     */
    public function getPayable(){
      return $this->_get(33);
    }
    
    /**
     * Set <payable> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setPayable( $value){
      return $this->_set(33, $value);
    }
    
    /**
     * Check if <quantity> has a value
     *
     * @return boolean
     */
    public function hasQuantity(){
      return $this->_has(35);
    }
    
    /**
     * Clear <quantity> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearQuantity(){
      return $this->_clear(35);
    }
    
    /**
     * Get <quantity> value
     *
     * @return int
     */
    public function getQuantity(){
      return $this->_get(35);
    }
    
    /**
     * Set <quantity> value
     *
     * @param int $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setQuantity( $value){
      return $this->_set(35, $value);
    }
    
    /**
     * Check if <tag_conditions> has a value
     *
     * @return boolean
     */
    public function hasTagConditions(){
      return $this->_has(36);
    }
    
    /**
     * Clear <tag_conditions> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearTagConditions(){
      return $this->_clear(36);
    }
    
    /**
     * Get <tag_conditions> value
     *
     * @param int $idx
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare\TagCondition
     */
    public function getTagConditions($idx = NULL){
      return $this->_get(36, $idx);
    }
    
    /**
     * Set <tag_conditions> value
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Product\Fare\TagCondition $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setTagConditions(\PlentyServices\TravelLibs\Protobuf\Product\Fare\TagCondition $value, $idx = NULL){
      return $this->_set(36, $value, $idx);
    }
    
    /**
     * Get all elements of <tag_conditions>
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare\TagCondition[]
     */
    public function getTagConditionsList(){
     return $this->_get(36);
    }
    
    /**
     * Add a new element to <tag_conditions>
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Product\Fare\TagCondition $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function addTagConditions(\PlentyServices\TravelLibs\Protobuf\Product\Fare\TagCondition $value){
     return $this->_add(36, $value);
    }
    
    /**
     * Check if <charges> has a value
     *
     * @return boolean
     */
    public function hasCharges(){
      return $this->_has(40);
    }
    
    /**
     * Clear <charges> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearCharges(){
      return $this->_clear(40);
    }
    
    /**
     * Get <charges> value
     *
     * @param int $idx
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare\Charge
     */
    public function getCharges($idx = NULL){
      return $this->_get(40, $idx);
    }
    
    /**
     * Set <charges> value
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Product\Fare\Charge $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setCharges(\PlentyServices\TravelLibs\Protobuf\Product\Fare\Charge $value, $idx = NULL){
      return $this->_set(40, $value, $idx);
    }
    
    /**
     * Get all elements of <charges>
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare\Charge[]
     */
    public function getChargesList(){
     return $this->_get(40);
    }
    
    /**
     * Add a new element to <charges>
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Product\Fare\Charge $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function addCharges(\PlentyServices\TravelLibs\Protobuf\Product\Fare\Charge $value){
     return $this->_add(40, $value);
    }
    
    /**
     * Check if <passengers> has a value
     *
     * @return boolean
     */
    public function hasPassengers(){
      return $this->_has(41);
    }
    
    /**
     * Clear <passengers> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearPassengers(){
      return $this->_clear(41);
    }
    
    /**
     * Get <passengers> value
     *
     * @param int $idx
     * @return \PlentyServices\TravelLibs\Protobuf\Person
     */
    public function getPassengers($idx = NULL){
      return $this->_get(41, $idx);
    }
    
    /**
     * Set <passengers> value
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Person $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setPassengers(\PlentyServices\TravelLibs\Protobuf\Person $value, $idx = NULL){
      return $this->_set(41, $value, $idx);
    }
    
    /**
     * Get all elements of <passengers>
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Person[]
     */
    public function getPassengersList(){
     return $this->_get(41);
    }
    
    /**
     * Add a new element to <passengers>
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Person $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function addPassengers(\PlentyServices\TravelLibs\Protobuf\Person $value){
     return $this->_add(41, $value);
    }
    
    /**
     * Check if <status> has a value
     *
     * @return boolean
     */
    public function hasStatus(){
      return $this->_has(42);
    }
    
    /**
     * Clear <status> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearStatus(){
      return $this->_clear(42);
    }
    
    /**
     * Get <status> value
     *
     * @return string
     */
    public function getStatus(){
      return $this->_get(42);
    }
    
    /**
     * Set <status> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setStatus( $value){
      return $this->_set(42, $value);
    }
    
    /**
     * Check if <condition_code> has a value
     *
     * @return boolean
     */
    public function hasConditionCode(){
      return $this->_has(50);
    }
    
    /**
     * Clear <condition_code> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearConditionCode(){
      return $this->_clear(50);
    }
    
    /**
     * Get <condition_code> value
     *
     * @return string
     */
    public function getConditionCode(){
      return $this->_get(50);
    }
    
    /**
     * Set <condition_code> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setConditionCode( $value){
      return $this->_set(50, $value);
    }
    
    /**
     * Check if <availability> has a value
     *
     * @return boolean
     */
    public function hasAvailability(){
      return $this->_has(51);
    }
    
    /**
     * Clear <availability> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearAvailability(){
      return $this->_clear(51);
    }
    
    /**
     * Get <availability> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Availability
     */
    public function getAvailability(){
      return $this->_get(51);
    }
    
    /**
     * Set <availability> value
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Availability $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setAvailability(\PlentyServices\TravelLibs\Protobuf\Availability $value){
      return $this->_set(51, $value);
    }
    
    /**
     * Check if <messages> has a value
     *
     * @return boolean
     */
    public function hasMessages(){
      return $this->_has(52);
    }
    
    /**
     * Clear <messages> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearMessages(){
      return $this->_clear(52);
    }
    
    /**
     * Get <messages> value
     *
     * @param int $idx
     * @return \PlentyServices\TravelLibs\Protobuf\Message
     */
    public function getMessages($idx = NULL){
      return $this->_get(52, $idx);
    }
    
    /**
     * Set <messages> value
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Message $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setMessages(\PlentyServices\TravelLibs\Protobuf\Message $value, $idx = NULL){
      return $this->_set(52, $value, $idx);
    }
    
    /**
     * Get all elements of <messages>
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Message[]
     */
    public function getMessagesList(){
     return $this->_get(52);
    }
    
    /**
     * Add a new element to <messages>
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Message $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function addMessages(\PlentyServices\TravelLibs\Protobuf\Message $value){
     return $this->_add(52, $value);
    }
    
    /**
     * Check if <offer_text> has a value
     *
     * @return boolean
     */
    public function hasOfferText(){
      return $this->_has(53);
    }
    
    /**
     * Clear <offer_text> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearOfferText(){
      return $this->_clear(53);
    }
    
    /**
     * Get <offer_text> value
     *
     * @return string
     */
    public function getOfferText(){
      return $this->_get(53);
    }
    
    /**
     * Set <offer_text> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setOfferText( $value){
      return $this->_set(53, $value);
    }
    
    /**
     * Check if <voucher_text> has a value
     *
     * @return boolean
     */
    public function hasVoucherText(){
      return $this->_has(55);
    }
    
    /**
     * Clear <voucher_text> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearVoucherText(){
      return $this->_clear(55);
    }
    
    /**
     * Get <voucher_text> value
     *
     * @return string
     */
    public function getVoucherText(){
      return $this->_get(55);
    }
    
    /**
     * Set <voucher_text> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setVoucherText( $value){
      return $this->_set(55, $value);
    }
    
    /**
     * Check if <booking_class> has a value
     *
     * @return boolean
     */
    public function hasBookingClass(){
      return $this->_has(56);
    }
    
    /**
     * Clear <booking_class> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearBookingClass(){
      return $this->_clear(56);
    }
    
    /**
     * Get <booking_class> value
     *
     * @return string
     */
    public function getBookingClass(){
      return $this->_get(56);
    }
    
    /**
     * Set <booking_class> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setBookingClass( $value){
      return $this->_set(56, $value);
    }
    
    /**
     * Check if <kilometers> has a value
     *
     * @return boolean
     */
    public function hasKilometers(){
      return $this->_has(57);
    }
    
    /**
     * Clear <kilometers> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearKilometers(){
      return $this->_clear(57);
    }
    
    /**
     * Get <kilometers> value
     *
     * @return int
     */
    public function getKilometers(){
      return $this->_get(57);
    }
    
    /**
     * Set <kilometers> value
     *
     * @param int $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setKilometers( $value){
      return $this->_set(57, $value);
    }
    
    /**
     * Check if <hidden> has a value
     *
     * @return boolean
     */
    public function hasHidden(){
      return $this->_has(58);
    }
    
    /**
     * Clear <hidden> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearHidden(){
      return $this->_clear(58);
    }
    
    /**
     * Get <hidden> value
     *
     * @return boolean
     */
    public function getHidden(){
      return $this->_get(58);
    }
    
    /**
     * Set <hidden> value
     *
     * @param boolean $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setHidden( $value){
      return $this->_set(58, $value);
    }
    
    /**
     * Check if <hide_retail_price> has a value
     *
     * @return boolean
     */
    public function hasHideRetailPrice(){
      return $this->_has(59);
    }
    
    /**
     * Clear <hide_retail_price> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearHideRetailPrice(){
      return $this->_clear(59);
    }
    
    /**
     * Get <hide_retail_price> value
     *
     * @return boolean
     */
    public function getHideRetailPrice(){
      return $this->_get(59);
    }
    
    /**
     * Set <hide_retail_price> value
     *
     * @param boolean $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setHideRetailPrice( $value){
      return $this->_set(59, $value);
    }
    
    /**
     * Check if <confirmation_number> has a value
     *
     * @return boolean
     */
    public function hasConfirmationNumber(){
      return $this->_has(60);
    }
    
    /**
     * Clear <confirmation_number> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearConfirmationNumber(){
      return $this->_clear(60);
    }
    
    /**
     * Get <confirmation_number> value
     *
     * @return string
     */
    public function getConfirmationNumber(){
      return $this->_get(60);
    }
    
    /**
     * Set <confirmation_number> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setConfirmationNumber( $value){
      return $this->_set(60, $value);
    }
    
    /**
     * Check if <external_reference> has a value
     *
     * @return boolean
     */
    public function hasExternalReference(){
      return $this->_has(61);
    }
    
    /**
     * Clear <external_reference> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function clearExternalReference(){
      return $this->_clear(61);
    }
    
    /**
     * Get <external_reference> value
     *
     * @return string
     */
    public function getExternalReference(){
      return $this->_get(61);
    }
    
    /**
     * Set <external_reference> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function setExternalReference( $value){
      return $this->_set(61, $value);
    }
  }
}

