<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: reservation.proto
//   Date: 2018-07-04 13:55:16

namespace PlentyServices\TravelLibs\Protobuf {

  class Package extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $name = null;
    
    /**  @var int */
    public $sort = null;
    
    /**  @var \PlentyServices\TravelLibs\Protobuf\Product[]  */
    public $products = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'PlentyServicesTravelLibs.Package');

      // REQUIRED STRING name = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // OPTIONAL INT32 sort = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "sort";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED MESSAGE products = 10
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10;
      $f->name      = "products";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\PlentyServices\TravelLibs\Protobuf\Product';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(1);
    }
    
    /**
     * Clear <name> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Package
     */
    public function clearName(){
      return $this->_clear(1);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(1);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Package
     */
    public function setName( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <sort> has a value
     *
     * @return boolean
     */
    public function hasSort(){
      return $this->_has(2);
    }
    
    /**
     * Clear <sort> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Package
     */
    public function clearSort(){
      return $this->_clear(2);
    }
    
    /**
     * Get <sort> value
     *
     * @return int
     */
    public function getSort(){
      return $this->_get(2);
    }
    
    /**
     * Set <sort> value
     *
     * @param int $value
     * @return \PlentyServices\TravelLibs\Protobuf\Package
     */
    public function setSort( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <products> has a value
     *
     * @return boolean
     */
    public function hasProducts(){
      return $this->_has(10);
    }
    
    /**
     * Clear <products> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Package
     */
    public function clearProducts(){
      return $this->_clear(10);
    }
    
    /**
     * Get <products> value
     *
     * @param int $idx
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function getProducts($idx = NULL){
      return $this->_get(10, $idx);
    }
    
    /**
     * Set <products> value
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Product $value
     * @return \PlentyServices\TravelLibs\Protobuf\Package
     */
    public function setProducts(\PlentyServices\TravelLibs\Protobuf\Product $value, $idx = NULL){
      return $this->_set(10, $value, $idx);
    }
    
    /**
     * Get all elements of <products>
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product[]
     */
    public function getProductsList(){
     return $this->_get(10);
    }
    
    /**
     * Add a new element to <products>
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Product $value
     * @return \PlentyServices\TravelLibs\Protobuf\Package
     */
    public function addProducts(\PlentyServices\TravelLibs\Protobuf\Product $value){
     return $this->_add(10, $value);
    }
  }
}

