<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: reservation.proto
//   Date: 2016-12-03 20:48:43

namespace PlentyServices\TravelLibs\Protobuf {

  class Product extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $product_uid = null;
    
    /**  @var string */
    public $product_alias = null;
    
    /**  @var string */
    public $vendor_uid = null;
    
    /**  @var string */
    public $vendor_alias = null;
    
    /**  @var string */
    public $product_type = null;
    
    /**  @var string */
    public $product_subtype = null;
    
    /**  @var string */
    public $display = null;
    
    /**  @var string */
    public $display_description = null;
    
    /**  @var string */
    public $from_place = null;
    
    /**  @var string */
    public $from_place_display = null;
    
    /**  @var string */
    public $from_date = null;
    
    /**  @var string */
    public $from_time = null;
    
    /**  @var string */
    public $to_place = null;
    
    /**  @var string */
    public $to_place_display = null;
    
    /**  @var string */
    public $to_date = null;
    
    /**  @var string */
    public $to_time = null;
    
    /**  @var \PlentyServices\TravelLibs\Protobuf\Product\Fare[]  */
    public $fares = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'PlentyServicesTravelLibs.Product');

      // OPTIONAL STRING product_uid = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "product_uid";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING product_alias = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "product_alias";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING vendor_uid = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "vendor_uid";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING vendor_alias = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "vendor_alias";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING product_type = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "product_type";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING product_subtype = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "product_subtype";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING display = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "display";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING display_description = 8
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 8;
      $f->name      = "display_description";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING from_place = 9
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 9;
      $f->name      = "from_place";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING from_place_display = 10
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10;
      $f->name      = "from_place_display";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING from_date = 11
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 11;
      $f->name      = "from_date";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING from_time = 12
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 12;
      $f->name      = "from_time";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING to_place = 15
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 15;
      $f->name      = "to_place";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING to_place_display = 16
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 16;
      $f->name      = "to_place_display";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING to_date = 17
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 17;
      $f->name      = "to_date";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING to_time = 18
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 18;
      $f->name      = "to_time";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED MESSAGE fares = 20
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 20;
      $f->name      = "fares";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\PlentyServices\TravelLibs\Protobuf\Product\Fare';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <product_uid> has a value
     *
     * @return boolean
     */
    public function hasProductUid(){
      return $this->_has(1);
    }
    
    /**
     * Clear <product_uid> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearProductUid(){
      return $this->_clear(1);
    }
    
    /**
     * Get <product_uid> value
     *
     * @return string
     */
    public function getProductUid(){
      return $this->_get(1);
    }
    
    /**
     * Set <product_uid> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setProductUid( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <product_alias> has a value
     *
     * @return boolean
     */
    public function hasProductAlias(){
      return $this->_has(2);
    }
    
    /**
     * Clear <product_alias> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearProductAlias(){
      return $this->_clear(2);
    }
    
    /**
     * Get <product_alias> value
     *
     * @return string
     */
    public function getProductAlias(){
      return $this->_get(2);
    }
    
    /**
     * Set <product_alias> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setProductAlias( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <vendor_uid> has a value
     *
     * @return boolean
     */
    public function hasVendorUid(){
      return $this->_has(3);
    }
    
    /**
     * Clear <vendor_uid> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearVendorUid(){
      return $this->_clear(3);
    }
    
    /**
     * Get <vendor_uid> value
     *
     * @return string
     */
    public function getVendorUid(){
      return $this->_get(3);
    }
    
    /**
     * Set <vendor_uid> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setVendorUid( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <vendor_alias> has a value
     *
     * @return boolean
     */
    public function hasVendorAlias(){
      return $this->_has(4);
    }
    
    /**
     * Clear <vendor_alias> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearVendorAlias(){
      return $this->_clear(4);
    }
    
    /**
     * Get <vendor_alias> value
     *
     * @return string
     */
    public function getVendorAlias(){
      return $this->_get(4);
    }
    
    /**
     * Set <vendor_alias> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setVendorAlias( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <product_type> has a value
     *
     * @return boolean
     */
    public function hasProductType(){
      return $this->_has(5);
    }
    
    /**
     * Clear <product_type> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearProductType(){
      return $this->_clear(5);
    }
    
    /**
     * Get <product_type> value
     *
     * @return string
     */
    public function getProductType(){
      return $this->_get(5);
    }
    
    /**
     * Set <product_type> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setProductType( $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <product_subtype> has a value
     *
     * @return boolean
     */
    public function hasProductSubtype(){
      return $this->_has(6);
    }
    
    /**
     * Clear <product_subtype> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearProductSubtype(){
      return $this->_clear(6);
    }
    
    /**
     * Get <product_subtype> value
     *
     * @return string
     */
    public function getProductSubtype(){
      return $this->_get(6);
    }
    
    /**
     * Set <product_subtype> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setProductSubtype( $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <display> has a value
     *
     * @return boolean
     */
    public function hasDisplay(){
      return $this->_has(7);
    }
    
    /**
     * Clear <display> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearDisplay(){
      return $this->_clear(7);
    }
    
    /**
     * Get <display> value
     *
     * @return string
     */
    public function getDisplay(){
      return $this->_get(7);
    }
    
    /**
     * Set <display> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setDisplay( $value){
      return $this->_set(7, $value);
    }
    
    /**
     * Check if <display_description> has a value
     *
     * @return boolean
     */
    public function hasDisplayDescription(){
      return $this->_has(8);
    }
    
    /**
     * Clear <display_description> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearDisplayDescription(){
      return $this->_clear(8);
    }
    
    /**
     * Get <display_description> value
     *
     * @return string
     */
    public function getDisplayDescription(){
      return $this->_get(8);
    }
    
    /**
     * Set <display_description> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setDisplayDescription( $value){
      return $this->_set(8, $value);
    }
    
    /**
     * Check if <from_place> has a value
     *
     * @return boolean
     */
    public function hasFromPlace(){
      return $this->_has(9);
    }
    
    /**
     * Clear <from_place> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearFromPlace(){
      return $this->_clear(9);
    }
    
    /**
     * Get <from_place> value
     *
     * @return string
     */
    public function getFromPlace(){
      return $this->_get(9);
    }
    
    /**
     * Set <from_place> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setFromPlace( $value){
      return $this->_set(9, $value);
    }
    
    /**
     * Check if <from_place_display> has a value
     *
     * @return boolean
     */
    public function hasFromPlaceDisplay(){
      return $this->_has(10);
    }
    
    /**
     * Clear <from_place_display> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearFromPlaceDisplay(){
      return $this->_clear(10);
    }
    
    /**
     * Get <from_place_display> value
     *
     * @return string
     */
    public function getFromPlaceDisplay(){
      return $this->_get(10);
    }
    
    /**
     * Set <from_place_display> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setFromPlaceDisplay( $value){
      return $this->_set(10, $value);
    }
    
    /**
     * Check if <from_date> has a value
     *
     * @return boolean
     */
    public function hasFromDate(){
      return $this->_has(11);
    }
    
    /**
     * Clear <from_date> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearFromDate(){
      return $this->_clear(11);
    }
    
    /**
     * Get <from_date> value
     *
     * @return string
     */
    public function getFromDate(){
      return $this->_get(11);
    }
    
    /**
     * Set <from_date> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setFromDate( $value){
      return $this->_set(11, $value);
    }
    
    /**
     * Check if <from_time> has a value
     *
     * @return boolean
     */
    public function hasFromTime(){
      return $this->_has(12);
    }
    
    /**
     * Clear <from_time> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearFromTime(){
      return $this->_clear(12);
    }
    
    /**
     * Get <from_time> value
     *
     * @return string
     */
    public function getFromTime(){
      return $this->_get(12);
    }
    
    /**
     * Set <from_time> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setFromTime( $value){
      return $this->_set(12, $value);
    }
    
    /**
     * Check if <to_place> has a value
     *
     * @return boolean
     */
    public function hasToPlace(){
      return $this->_has(15);
    }
    
    /**
     * Clear <to_place> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearToPlace(){
      return $this->_clear(15);
    }
    
    /**
     * Get <to_place> value
     *
     * @return string
     */
    public function getToPlace(){
      return $this->_get(15);
    }
    
    /**
     * Set <to_place> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setToPlace( $value){
      return $this->_set(15, $value);
    }
    
    /**
     * Check if <to_place_display> has a value
     *
     * @return boolean
     */
    public function hasToPlaceDisplay(){
      return $this->_has(16);
    }
    
    /**
     * Clear <to_place_display> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearToPlaceDisplay(){
      return $this->_clear(16);
    }
    
    /**
     * Get <to_place_display> value
     *
     * @return string
     */
    public function getToPlaceDisplay(){
      return $this->_get(16);
    }
    
    /**
     * Set <to_place_display> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setToPlaceDisplay( $value){
      return $this->_set(16, $value);
    }
    
    /**
     * Check if <to_date> has a value
     *
     * @return boolean
     */
    public function hasToDate(){
      return $this->_has(17);
    }
    
    /**
     * Clear <to_date> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearToDate(){
      return $this->_clear(17);
    }
    
    /**
     * Get <to_date> value
     *
     * @return string
     */
    public function getToDate(){
      return $this->_get(17);
    }
    
    /**
     * Set <to_date> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setToDate( $value){
      return $this->_set(17, $value);
    }
    
    /**
     * Check if <to_time> has a value
     *
     * @return boolean
     */
    public function hasToTime(){
      return $this->_has(18);
    }
    
    /**
     * Clear <to_time> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearToTime(){
      return $this->_clear(18);
    }
    
    /**
     * Get <to_time> value
     *
     * @return string
     */
    public function getToTime(){
      return $this->_get(18);
    }
    
    /**
     * Set <to_time> value
     *
     * @param string $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setToTime( $value){
      return $this->_set(18, $value);
    }
    
    /**
     * Check if <fares> has a value
     *
     * @return boolean
     */
    public function hasFares(){
      return $this->_has(20);
    }
    
    /**
     * Clear <fares> value
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function clearFares(){
      return $this->_clear(20);
    }
    
    /**
     * Get <fares> value
     *
     * @param int $idx
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare
     */
    public function getFares($idx = NULL){
      return $this->_get(20, $idx);
    }
    
    /**
     * Set <fares> value
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Product\Fare $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function setFares(\PlentyServices\TravelLibs\Protobuf\Product\Fare $value, $idx = NULL){
      return $this->_set(20, $value, $idx);
    }
    
    /**
     * Get all elements of <fares>
     *
     * @return \PlentyServices\TravelLibs\Protobuf\Product\Fare[]
     */
    public function getFaresList(){
     return $this->_get(20);
    }
    
    /**
     * Add a new element to <fares>
     *
     * @param \PlentyServices\TravelLibs\Protobuf\Product\Fare $value
     * @return \PlentyServices\TravelLibs\Protobuf\Product
     */
    public function addFares(\PlentyServices\TravelLibs\Protobuf\Product\Fare $value){
     return $this->_add(20, $value);
    }
  }
}

