<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: reservation.proto
//   Date: 2017-07-12 07:23:56

namespace PlentyServices\TravelLibs\Protobuf\Message {

  class Access extends \DrSlump\Protobuf\Enum {
    const ANY = 0;
    const OPERATOR = 1;
    const CONSULANT = 2;
    const BROKER = 3;
    const PEER = 4;
  }
}
