<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reservation.proto

namespace Plenty;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Reservation extends \Google\Protobuf\Internal\Message
{
    private $general = null;

    public function getGeneral()
    {
        return $this->general;
    }

    public function setGeneral(&$var)
    {
        GPBUtil::checkMessage($var, \Plenty\General::class);
        $this->general = $var;
    }

}

class General extends \Google\Protobuf\Internal\Message
{
    private $status = 0;
    private $system = 0;
    private $transaction_type = 0;
    private $operator = '';
    private $peer = '';
    private $broker = '';
    private $travel_type = '';
    private $travel_type_sub = '';
    private $display = '';
    private $currency = '';
    private $locale = '';
    private $payment_type = 0;
    private $payment_surcharge_amount = 0.0;
    private $payment_surcharge_percentage = 0;
    private $ip_reffered = '';
    private $consultant_notice;
    private $contractor_notice;

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Plenty\General_Status::class);
        $this->status = $var;
    }

    public function getSystem()
    {
        return $this->system;
    }

    public function setSystem($var)
    {
        GPBUtil::checkEnum($var, \Plenty\General_System::class);
        $this->system = $var;
    }

    public function getTransactionType()
    {
        return $this->transaction_type;
    }

    public function setTransactionType($var)
    {
        GPBUtil::checkEnum($var, \Plenty\General_TransactionType::class);
        $this->transaction_type = $var;
    }

    public function getOperator()
    {
        return $this->operator;
    }

    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->operator = $var;
    }

    public function getPeer()
    {
        return $this->peer;
    }

    public function setPeer($var)
    {
        GPBUtil::checkString($var, True);
        $this->peer = $var;
    }

    public function getBroker()
    {
        return $this->broker;
    }

    public function setBroker($var)
    {
        GPBUtil::checkString($var, True);
        $this->broker = $var;
    }

    public function getTravelType()
    {
        return $this->travel_type;
    }

    public function setTravelType($var)
    {
        GPBUtil::checkString($var, True);
        $this->travel_type = $var;
    }

    public function getTravelTypeSub()
    {
        return $this->travel_type_sub;
    }

    public function setTravelTypeSub($var)
    {
        GPBUtil::checkString($var, True);
        $this->travel_type_sub = $var;
    }

    public function getDisplay()
    {
        return $this->display;
    }

    public function setDisplay($var)
    {
        GPBUtil::checkString($var, True);
        $this->display = $var;
    }

    public function getCurrency()
    {
        return $this->currency;
    }

    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;
    }

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($var)
    {
        GPBUtil::checkString($var, True);
        $this->locale = $var;
    }

    public function getPaymentType()
    {
        return $this->payment_type;
    }

    public function setPaymentType($var)
    {
        GPBUtil::checkEnum($var, \Plenty\General_PaymentType::class);
        $this->payment_type = $var;
    }

    public function getPaymentSurchargeAmount()
    {
        return $this->payment_surcharge_amount;
    }

    public function setPaymentSurchargeAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->payment_surcharge_amount = $var;
    }

    public function getPaymentSurchargePercentage()
    {
        return $this->payment_surcharge_percentage;
    }

    public function setPaymentSurchargePercentage($var)
    {
        GPBUtil::checkInt32($var);
        $this->payment_surcharge_percentage = $var;
    }

    public function getIpReffered()
    {
        return $this->ip_reffered;
    }

    public function setIpReffered($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip_reffered = $var;
    }

    public function getConsultantNotice()
    {
        return $this->consultant_notice;
    }

    public function setConsultantNotice(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->consultant_notice = $var;
    }

    public function getContractorNotice()
    {
        return $this->contractor_notice;
    }

    public function setContractorNotice(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->contractor_notice = $var;
    }

}

class General_Status
{
    const request = 0;
    const booking = 1;
}

class General_System
{
    const travel = 0;
    const camper = 1;
}

class General_TransactionType
{
    const direct = 0;
    const reseller = 1;
}

class General_PaymentType
{
    const invoice = 0;
    const credit_card = 1;
}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ae2050a117265736572766174696f6e2e70726f746f1206706c656e7479" .
    "222f0a0b5265736572766174696f6e12200a0767656e6572616c18012001" .
    "280b320f2e706c656e74792e47656e6572616c228b050a0747656e657261" .
    "6c12260a0673746174757318012001280e32162e706c656e74792e47656e" .
    "6572616c2e53746174757312260a0673797374656d18022001280e32162e" .
    "706c656e74792e47656e6572616c2e53797374656d12390a107472616e73" .
    "616374696f6e5f7479706518032001280e321f2e706c656e74792e47656e" .
    "6572616c2e5472616e73616374696f6e5479706512100a086f7065726174" .
    "6f72180420012809120c0a0470656572180520012809120e0a0662726f6b" .
    "657218062001280912130a0b74726176656c5f7479706518072001280912" .
    "170a0f74726176656c5f747970655f737562180820012809120f0a076469" .
    "73706c617918092001280912100a0863757272656e6379180a2001280912" .
    "0e0a066c6f63616c65180b2001280912310a0c7061796d656e745f747970" .
    "65180c2001280e321b2e706c656e74792e47656e6572616c2e5061796d65" .
    "6e745479706512200a187061796d656e745f7375726368617267655f616d" .
    "6f756e74180d2001280112240a1c7061796d656e745f7375726368617267" .
    "655f70657263656e74616765180e2001280512130a0b69705f7265666665" .
    "726564180f2001280912190a11636f6e73756c74616e745f6e6f74696365" .
    "18102003280912190a11636f6e74726163746f725f6e6f74696365181120" .
    "03280922220a06537461747573120b0a07726571756573741000120b0a07" .
    "626f6f6b696e67100122200a0653797374656d120a0a0674726176656c10" .
    "00120a0a0663616d7065721001222b0a0f5472616e73616374696f6e5479" .
    "7065120a0a066469726563741000120c0a08726573656c6c65721001222b" .
    "0a0b5061796d656e7454797065120b0a07696e766f6963651000120f0a0b" .
    "6372656469745f636172641001620670726f746f33"
));